DEBUG: 2021-06-30 21:31:12,341: Data.py: <module>: Logs\KNN_results_20210630_213112\classifier.log
